import './style.css';
import './zoom.css';
import './ticket-style.css';
import './copy.css';
import './overrides.css';
import './input-fix.css';
import './timer.css';
import './result-modal.css';
import './crowd.css';
import './rank-size.css';
import './result-sections.css';
import './rank-times.css';
import './waiting.css';
import './header-clean.css';
import './posters.css';
import './captcha-mobile.css';
document.addEventListener('dblclick', event => event.preventDefault(), { passive: false });
const shows=[
 {id:'crown',category:'콘서트',artist:'VANTA',title:'THE CROWN : FINAL',poster:'posters/crown.jpg',sub:'SEOUL · GOCHEOK SKY DOME',date:'10.12 SAT 7PM',difficulty:'VERY HARD',audience:'42,816',lockedRange:[27,33],loss:.8,theme:'purple',opening:true},
 {id:'neon',category:'팬미팅',artist:'ASTER',title:'NEON WAVE WORLD TOUR',poster:'posters/neon.jpg',sub:'SEOUL · OLYMPIC HALL',date:'08.24 SAT 7PM',difficulty:'HARD',audience:'18,742',lockedRange:[18,26],loss:.55,theme:'purple'},
 {id:'horizon',category:'뮤지컬',artist:'MELLOWDAY',title:'HORIZON FAN CONCERT',poster:'posters/horizon.jpg',sub:'SEOUL · KSPO DOME',date:'09.07 SAT 6PM',difficulty:'NORMAL',audience:'7,386',lockedRange:[10,18],loss:.28,theme:'orange'},
 {id:'luna',category:'콘서트',artist:'콘서트',title:'LUNA ACOUSTIC NIGHT',sub:'SEOUL · BLUE SQUARE',date:'09.21 SAT 8PM',difficulty:'EASY',audience:'1,924',lockedRange:[4,11],loss:.12,theme:'blue'}
];
const allRows=[['A','VIP','154,000원',740],['B','S','132,000원',540],['C','A','110,000원',360],['D','A','110,000원',360],['E','B','88,000원',180],['F','B','88,000원',180],['G','B','88,000원',180]];
let rows=allRows.slice(0,4);
const baseLocked=[];
const state={stage:'list',show:null,picked:null,started:0,openingStarted:0,queueJoinDelay:0,captchaTime:0,bookingTime:0,score:0,locked:new Set(baseLocked),captcha:'',timer:null,waitTimer:null,countdown:0,queueNumber:0,queueStart:0,conflict:false,soldout:false,completed:false};
const app=document.querySelector('#app');
const meta=id=>allRows.find(r=>r[0]===id[0]); const rank=()=>state.score>=850?['S+','TICKETING GOD']:state.score>=700?['S','FRONT ROW']:state.score>=550?['A','QUICK HAND']:state.score>=400?['B','GOOD TRY']:state.score>=250?['C','KEEP GOING']:['D','NEXT TIME'];
const rankMessage=grade=>({ 'S+':'전설의 손속도! 최고의 자리를 완벽하게 잡았어요.','S':'치열한 경쟁을 뚫은 프론트 로우 헌터예요.','A':'빠르고 정확한 예매 실력이에요.','B':'좋아요! 다음엔 더 빠르게 도전해보세요.','C':'끝까지 도전한 당신, 다음 기회는 더 좋아요.','D':'예매 전쟁은 계속됩니다. 다시 도전해보세요.' }[grade]);
const elapsed=()=>state.started?((performance.now()-state.started)/1000).toFixed(2):'0.00';
function render(){let view=state.stage==='list'?list():state.stage==='openwait'?openwait():state.stage==='queue'?queue():state.stage==='captcha'?captcha():state.stage==='seat'?seats():result();app.innerHTML=`<div class="phone"><header><b>FROG TICKET <i>GAME</i></b></header>${state.stage!=='list'?'<div class="progress"><i></i><i class="on"></i><i></i></div>':''}${view}</div>${state.conflict||state.soldout||state.completed?modal():''}<div class="toast" id="toast"></div>`;bind()}
function list(){return `<main class="list"><div class="list-title"><span>CONCERT TICKETING GAME</span><h1>어떤 공연을<br>예매할까요?</h1><p>난이도가 높을수록 경쟁자는 많고 빈 좌석은 적어요.</p></div><div class="show-list">${shows.map(s=>`<button class="show-card ${s.theme}" data-show="${s.id}"><div class="mini-poster ${s.poster?'has-poster':'luna-poster'}" ${s.poster?`style="background-image:url('${s.poster}')"`:''}><b>${s.id==='neon'?'NEON<br>WAVE':s.id==='horizon'?'HORIZON':s.id==='luna'?'LUNA':'THE<br>CROWN'}</b></div><div class="show-copy"><small class="artist">${s.category} · ${s.artist}</small><strong>${s.title}</strong><span>${s.sub}<br>${s.date}</span><em class="${s.difficulty.toLowerCase()}">● ${s.audience}명 동시 예매 · ${s.difficulty}</em></div><i>›</i></button>`).join('')}</div></main>`}
function openwait(){return `<main class="wait-page open-ready-page"><span class="step">TICKET OPEN WAITING</span><div class="ready-icon">🍇</div><h1>티켓 오픈 대기중</h1><p><b>${state.show.title}</b><br>시작 전 손가락을 풀어주세요~</p><div class="open-count"><b>${state.countdown}</b></div><small>카운트다운이 끝나면 예매하기 버튼이 열립니다.</small><button class="cta" id="joinQueue" ${state.countdown?'disabled':''}>${state.countdown?'티켓 오픈 대기 중':'예매하기'}</button></main>`}
function readyScreen(){return `<main class="wait-page ready-page"><span class="step">GET READY</span><div class="ready-icon">🍇</div><h1>시작 전<br>손가락을 풀어주세요~</h1><p>잠시 후 예매가 시작됩니다.<br>이 준비 시간에는 좌석이 사라지지 않아요.</p><div class="ready-count"><b>${state.readyCountdown}</b></div><small>카운트다운이 끝나면 예매가 바로 시작됩니다.</small></main>`}
function queue(){const progress=Math.max(0,100-Math.round(state.queueNumber/state.queueStart*100));return `<main class="wait-page queue-page"><span class="step">BOOKING QUEUE</span><h1>예매 대기열<br>접속 중</h1><p>${state.show.audience}명의 예매자와 함께 접속하고 있어요.</p><div class="queue-number">앞에 남은 대기 인원<br><b>${state.queueNumber.toLocaleString()}명</b></div><div class="queue-bar"><i style="width:${progress}%"></i></div><small>대기 인원이 0명이 되면 보안문자 입력이 시작됩니다.</small></main>`}
function captcha(){return `<main class="captcha-page"><div class="captcha-timer"><small>실시간 예매 경쟁 진행 중</small><b>LIVE</b></div><span class="step">STEP 01 / SECURITY CHECK</span><h1>안심 예매<br>보안문자 입력</h1><p>보안문자 통과 시간도 최종 랭크에 반영됩니다.</p><div class="captcha-code">${[...state.captcha].map((x,i)=>`<b class="c${i}">${x}</b>`).join('')}</div><input id="input" type="text" inputmode="latin" lang="en" autocapitalize="characters" autocomplete="off" autocorrect="off" spellcheck="false" maxlength="6" placeholder="보안문자 6자리 입력" aria-label="보안문자 입력" autofocus><p class="hint">한글 입력 상태여도 키보드의 영문·숫자 키로 입력됩니다.</p><button class="cta" id="verify">확인</button></main>`}
function seats(){
  const selected=state.picked&&meta(state.picked);
  const status=selected
    ? `<strong>${state.picked} · ${selected[1]}석</strong><span>${selected[2]}</span>`
    : `<strong>${state.expired?'예매 시간이 종료되었습니다':'좌석을 선택해주세요'}</strong><span>${state.expired?'다시 도전하려면 공연 목록으로 이동하세요':'높은 등급일수록 보너스가 커요'}</span>`;
  return `<main class="booking"><div class="booking-head"><div><span class="step">STEP 02 / SEAT SELECT</span><h1>좌석 선택</h1></div><div class="timer"><small>좌석 경쟁</small><b>LIVE</b></div></div><div class="show-strip"><b>${state.show.title}</b><span class="crowd">● 현재 ${state.show.audience}명과 동시 예매 중 · 실시간 소진 중</span></div><div class="venue"><div class="stage">STAGE</div><div class="legend"><span><i class="vip"></i>VIP</span><span><i class="r"></i>R</span><span><i class="s"></i>S</span><span><i class="used"></i>선택불가</span></div>${rows.map(([r,g])=>`<div class="seat-line"><b>${r}<small>${g}</small></b><div>${Array.from({length:10},(_,n)=>{const id=r+(n+1),lock=state.locked.has(id);return `<button class="seat ${g.toLowerCase()} ${lock?'locked':''} ${state.picked===id?'chosen':''}" data-seat="${id}" ${lock?'disabled':''}>${n+1}</button>`}).join('')}</div></div>`).join('')}</div><div class="seat-info"><div>${status}</div><button id="book" ${selected?'':'disabled'}>선택 완료</button></div></main>`
}
function result(){let m=meta(state.picked),[g,n]=rank();return `<main class="result"><div class="success">✓</div><span class="step">BOOKING SUCCESS</span><h1>예매 성공!</h1><p><b>${state.picked} ${m[1]}석</b>을 확보했어요.</p><div class="ticket"><div><span>${state.show.title}</span><b>${state.picked}</b><small>${state.show.date}</small></div><i></i><strong>${m[1]}<small>${m[2]}</small></strong></div><div class="result-grid"><div><small>REACTION TIME</small><b>${state.reaction}초</b><span>보안문자 통과 후 좌석 선택</span></div><div><small>SEAT GRADE</small><b>${m[1]}</b><span>좌석 등급 보너스</span></div></div><div class="rank-result"><span>YOUR RANK</span><b>${g}</b><div><strong>${n}</strong><p>${state.score} PT · 예매 실력 인증!</p></div></div><button class="cta" id="restart">공연 목록으로</button></main>`}
function modal(){if(state.completed){const [g,n]=rank(),seat=meta(state.picked);return `<div class="modal-backdrop"><div class="seat-modal result-modal"><div>✓</div><h2>예매 완료!</h2><section class="result-block booking-detail"><small>BOOKING DETAILS</small><b>${state.show.artist} · ${state.show.title}</b><span>${state.show.sub}</span><strong>${state.picked} ${seat[1]}석 · ${seat[2]}</strong></section><section class="result-block rank-block"><small>YOUR RANK</small><div class="big-rank">${g}</div><strong class="rank-name">${n}</strong><p class="rank-message">${rankMessage(g)}</p><div class="rank-times"><span>보안문자 해독 <b>${state.captchaTime}초</b></span><span>예매 완료 <b>${state.bookingTime}초</b></span></div></section><button id="retry">다시 도전하기</button></div></div>`}const sold=state.soldout;return `<div class="modal-backdrop"><div class="seat-modal"><div>${sold?'×':'!'}</div><h2>${sold?'SOLD OUT':'이미 선택된 좌석입니다'}</h2><p>${sold?'선택 가능한 모든 좌석이 소진되었습니다.<br><strong>아쉬워요. 민첩한 하루 되세요!</strong>':'다른 예매자가 먼저 선택한 좌석이에요.'}</p><button id="close">${sold?'다른 공연 예매하기':'확인'}</button></div></div>`}
function bind(){let q=s=>document.querySelector(s);document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>{state.show=shows.find(s=>s.id===b.dataset.show);if(state.show.opening){state.countdown=10;state.stage='openwait';state.waitTimer=setInterval(()=>{state.countdown--;if(state.countdown<=0){clearInterval(state.waitTimer);state.countdown=0}render()},1000);render()}else beginBooking()});if(q('#joinQueue'))q('#joinQueue').onclick=()=>{const congestion=Math.round((Math.sin(Date.now()/850)+1)*18);state.queueNumber=18+congestion;state.queueStart=state.queueNumber;state.stage='queue';state.waitTimer=setInterval(()=>{const processed=3+Math.round((Math.sin(Date.now()/420)+1)*3);state.queueNumber=Math.max(0,state.queueNumber-processed);if(state.queueNumber===0){clearInterval(state.waitTimer);beginBooking()}else render()},500);render()};if(q('#verify'))q('#verify').onclick=verify;if(q('#input')){const input=q('#input');input.oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');input.onkeydown=e=>{if(e.key==='Enter'){verify();return}if(e.key==='Backspace'){e.preventDefault();input.value=input.value.slice(0,-1);return}const letter=e.code.match(/^Key([A-Z])$/),digit=e.code.match(/^Digit([0-9])$/);if(letter||digit){e.preventDefault();input.value=(input.value+(letter?.[1]||digit?.[1])).slice(0,6)}};setTimeout(()=>input.focus(),0)}document.querySelectorAll('.seat:not(.locked)').forEach(b=>b.onclick=()=>{state.picked=b.dataset.seat;render()});if(q('#book'))q('#book').onclick=book;if(q('#close'))q('#close').onclick=()=>{if(state.soldout)reset();else{state.conflict=false;render()}};if(q('#retry'))q('#retry').onclick=reset;if(q('#share'))q('#share').onclick=shareResult;if(q('#restart'))q('#restart').onclick=reset}

function startVeryHardQueue(){
  const openedAt=state.openingStarted+10000;
  const lateSeconds=Math.max(0,(Date.now()-openedAt)/1000);
  const openingRush=3200+Math.floor(Math.random()*1400)+Math.round((Math.sin(Date.now()/900)+1)*650);
  const lateArrival=Math.min(10000,Math.round(lateSeconds*170+Math.pow(lateSeconds,1.2)*25));
  state.queueJoinDelay=Math.floor(lateSeconds);
  state.queueNumber=Math.min(18000,openingRush+lateArrival);
  state.queueStart=state.queueNumber;
  state.stage='queue';
  state.waitTimer=setInterval(()=>{
    const processed=130+Math.floor(Math.random()*120)+Math.round((Math.sin(Date.now()/430)+1)*45);
    state.queueNumber=Math.max(0,state.queueNumber-processed);
    if(state.queueNumber===0){clearInterval(state.waitTimer);beginBooking()}else render()
  },500);
  render()
}
function queueNew(){const progress=Math.max(0,100-Math.round(state.queueNumber/state.queueStart*100));const timing=state.queueJoinDelay?`오픈 ${state.queueJoinDelay}초 후 접속`:'오픈 직후 접속';return `<main class="wait-page queue-page"><span class="step">BOOKING QUEUE</span><h1>예매 대기열<br>접속 중</h1><p>${timing} · ${state.show.audience}명의 예매자와 함께 접속하고 있어요.</p><div class="queue-number">앞에 남은 대기 인원<br><b>${state.queueNumber.toLocaleString()}명</b></div><div class="queue-bar"><i style="width:${progress}%"></i></div><small>오픈 직후 접속 폭주로 실시간 대기열이 반영됩니다.</small></main>`}
function bindNew(){let q=s=>document.querySelector(s);document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>{state.show=shows.find(s=>s.id===b.dataset.show);if(state.show.opening){state.openingStarted=Date.now();state.countdown=10;state.stage='openwait';state.waitTimer=setInterval(()=>{state.countdown--;if(state.countdown<=0){clearInterval(state.waitTimer);state.countdown=0}render()},1000);render()}else beginBooking()});if(q('#joinQueue'))q('#joinQueue').onclick=startVeryHardQueue;if(q('#verify'))q('#verify').onclick=verify;if(q('#input')){const input=q('#input');input.oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');input.onkeydown=e=>{if(e.key==='Enter'){verify();return}if(e.key==='Backspace'){e.preventDefault();input.value=input.value.slice(0,-1);return}const letter=e.code.match(/^Key([A-Z])$/),digit=e.code.match(/^Digit([0-9])$/);if(letter||digit){e.preventDefault();input.value=(input.value+(letter?.[1]||digit?.[1])).slice(0,6)}};setTimeout(()=>input.focus(),0)}document.querySelectorAll('.seat:not(.locked)').forEach(b=>b.onclick=()=>{state.picked=b.dataset.seat;render()});if(q('#book'))q('#book').onclick=book;if(q('#close'))q('#close').onclick=()=>{if(state.soldout)reset();else{state.conflict=false;render()}};if(q('#retry'))q('#retry').onclick=reset;if(q('#share'))q('#share').onclick=shareResult;if(q('#restart'))q('#restart').onclick=reset}
queue=queueNew;
bind=bindNew;
function listNew(){return `<main class="list"><div class="list-title"><span>CONCERT TICKETING GAME</span><h1>티켓팅 전쟁</h1><p>과연 무사히 공연에 갈 수 있을까?<br>행운을 빕니다.</p></div><div class="show-list">${shows.map(s=>`<button class="show-card ${s.theme}" data-show="${s.id}"><div class="mini-poster ${s.poster?'has-poster':'luna-poster'}" ${s.poster?`style="background-image:url('${s.poster}')"`:''}><b>${s.id==='neon'?'NEON<br>WAVE':s.id==='horizon'?'HORIZON':s.id==='luna'?'LUNA':'THE<br>CROWN'}</b></div><div class="show-copy"><small class="artist">${s.category} · ${s.artist}</small><strong>${s.title}</strong><span>${s.sub}<br>${s.date}</span><em class="${s.difficulty.toLowerCase()}">● 예매 전쟁 진행 중 · ${s.difficulty}</em></div><i>›</i></button>`).join('')}</div></main>`}
function queueLatest(){const progress=Math.max(0,100-Math.round(state.queueNumber/state.queueStart*100));const timing=state.queueJoinDelay?`오픈 ${state.queueJoinDelay}초 후 접속`:'오픈 직후 접속';return `<main class="wait-page queue-page"><span class="step">BOOKING QUEUE</span><h1>예매 대기열<br>접속 중</h1><p>${timing} · 예매자가 한꺼번에 몰리고 있어요.</p><div class="queue-number">앞에 남은 대기 인원<br><b>${state.queueNumber.toLocaleString()}명</b></div><div class="queue-bar"><i style="width:${progress}%"></i></div><small>오픈 직후 접속 폭주로 실시간 대기열이 반영됩니다.</small></main>`}
list=listNew;
queue=queueLatest;
function listLatest(){return `<main class="list"><div class="list-title"><span>CONCERT TICKETING GAME</span><h1>티켓팅 전쟁</h1><p>과연 무사히 공연에 갈 수 있을까?<br>행운을 빕니다.</p></div><div class="show-list">${shows.map(s=>`<button class="show-card ${s.theme}" data-show="${s.id}"><div class="mini-poster ${s.poster?'has-poster':'luna-poster'}" ${s.poster?`style="background-image:url('${s.poster}')"`:''}><b>${s.id==='neon'?'NEON<br>WAVE':s.id==='horizon'?'HORIZON':s.id==='luna'?'LUNA':'THE<br>CROWN'}</b></div><div class="show-copy"><strong>${s.title}</strong><span>${s.sub}<br>${s.date}</span><em class="difficulty-badge ${s.difficulty.toLowerCase().replace(' ','-')}">${s.difficulty}</em></div><i>›</i></button>`).join('')}</div></main>`}
list=listLatest;
function listFinal(){return `<main class="list"><div class="list-title"><span>CONCERT TICKETING GAME</span><h1>포도알 구하기 🍇</h1><p>과연 무사히 공연에 갈 수 있을까?<br>행운을 빕니다.. (낄낄..)</p></div><div class="show-list">${shows.map(s=>`<button class="show-card ${s.theme}" data-show="${s.id}"><div class="mini-poster ${s.poster?'has-poster':'luna-poster'}" ${s.poster?`style="background-image:url('${s.poster}')"`:''}><b>${s.id==='neon'?'NEON<br>WAVE':s.id==='horizon'?'HORIZON':s.id==='luna'?'LUNA':'THE<br>CROWN'}</b></div><div class="show-copy"><strong>${s.title}</strong><span>${s.sub}<br>${s.date}</span><em class="difficulty-badge ${s.difficulty.toLowerCase().replace(' ','-')}">${s.difficulty}</em></div><i>›</i></button>`).join('')}</div></main>`}
list=listFinal;
function beginBooking(){rows=state.show.opening?allRows:state.show.difficulty==='HARD'?allRows.slice(0,5):allRows.slice(0,4);state.locked=new Set(randomLocked(state.show));state.captcha=makeCaptcha();state.started=performance.now();state.soldout=false;state.completed=false;state.stage='captcha';state.timer=setTimeout(scheduleLoss,lossDelay());render()}

function beginBookingEasy(){rows=state.show.opening?allRows:state.show.difficulty==='HARD'?allRows.slice(0,5):allRows.slice(0,4);state.locked=new Set(randomLocked(state.show));state.captcha=makeCaptcha();state.started=performance.now();state.captchaTime=0;state.soldout=false;state.completed=false;state.stage=state.show.difficulty==='EASY'?'seat':'captcha';state.timer=setTimeout(scheduleLoss,lossDelay());render()}
beginBooking=beginBookingEasy;
const baseVeryHardQueue=startVeryHardQueue;
function startVeryHardQueueFinal(){state.hadQueue=true;state.queueEntrySpeed=Math.max(0,(Date.now()-(state.openingStarted+10000))/1000).toFixed(2);baseVeryHardQueue()}
startVeryHardQueue=startVeryHardQueueFinal;
function startHardQueue(){state.hadQueue=true;state.queueJoinDelay=0;state.queueEntrySpeed=((Date.now()-state.openingStarted)/1000).toFixed(2);state.queueNumber=300+Math.floor(Math.random()*360);state.queueStart=state.queueNumber;state.stage='queue';state.waitTimer=setInterval(()=>{const processed=45+Math.floor(Math.random()*65);state.queueNumber=Math.max(0,state.queueNumber-processed);if(state.queueNumber===0){clearInterval(state.waitTimer);beginBooking()}else render()},500);render()}
function queueFinal(){const progress=Math.max(0,100-Math.round(state.queueNumber/state.queueStart*100));const timing=state.show.difficulty==='HARD'?'공연 선택 직후 대기열 진입':state.queueJoinDelay?`오픈 ${state.queueJoinDelay}초 후 접속`:'오픈 직후 접속';return `<main class="wait-page queue-page"><span class="step">BOOKING QUEUE</span><h1>예매 대기열<br>접속 중</h1><p>${timing} · 예매자가 한꺼번에 몰리고 있어요.</p><div class="queue-number">앞에 남은 대기 인원<br><b>${state.queueNumber.toLocaleString()}명</b></div><div class="queue-bar"><i style="width:${progress}%"></i></div><small>실시간 대기열이 반영됩니다.</small></main>`}
queue=queueFinal;
function bindFinal(){bindNew();document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>{state.show=shows.find(s=>s.id===b.dataset.show);state.hadQueue=false;state.queueStart=0;state.queueJoinDelay=0;state.queueEntrySpeed='';if(state.show.opening){state.openingStarted=Date.now();state.countdown=10;state.stage='openwait';state.waitTimer=setInterval(()=>{state.countdown--;if(state.countdown<=0){clearInterval(state.waitTimer);state.countdown=0}render()},1000);render()}else if(state.show.difficulty==='HARD'){state.openingStarted=Date.now();startHardQueue()}else beginBooking()})}
bind=bindFinal;
const baseModal=modal;
function competitionRate(){const seats=rows.length*10;const players=state.hadQueue?state.queueStart+seats:state.show.difficulty==='NORMAL'?180:70;return Math.max(1,Math.round(players/seats))}
function modalFinal(){if(!state.completed)return baseModal();const [g,n]=rank(),seat=meta(state.picked),queueInfo=state.hadQueue?`<span>대기열 진입 <b>${state.queueEntrySpeed}초</b></span>`:'';return `<div class="modal-backdrop"><div class="seat-modal result-modal"><div>✓</div><h2>예매 완료!</h2><section class="result-block booking-detail"><small>BOOKING DETAILS</small><b>${state.show.artist} · ${state.show.title}</b><span>${state.show.sub}</span><strong>${state.picked} ${seat[1]}석 · ${seat[2]}</strong></section><section class="result-block rank-block"><small>YOUR RANK</small><div class="big-rank">${g}</div><strong class="rank-name">${n}</strong><p class="rank-message">${rankMessage(g)}</p><div class="rank-times"><span>경쟁률 <b>약 ${competitionRate()} : 1</b></span>${queueInfo}<span>보안문자 해독 <b>${state.captchaTime}초</b></span><span>예매 완료 <b>${state.bookingTime}초</b></span></div></section><button id="retry">다시 도전하기</button></div></div>`}
modal=modalFinal;
const modalBeforeSoldout=modal;
function modalSoldout(){if(!state.soldout)return modalBeforeSoldout();return `<div class="modal-backdrop soldout-backdrop"><div class="soldout-panel"><span class="soldout-eyebrow">ALL SEATS SOLD OUT</span><div class="soldout-icon">🍇</div><h2>이번 포도알은<br>이미 모두 사라졌어요.</h2><p>치열한 예매 전쟁이었어요.<br><strong>아쉬워요. 민첩한 하루 되세요!</strong></p><div class="soldout-note">다음 공연에서 더 빠르게 도전해봐요.</div><button id="close">다른 공연 예매하기</button></div></div>`}
modal=modalSoldout;
const modalBeforeSoldoutPopup=modal;
function modalSoldoutPopup(){if(!state.soldout)return modalBeforeSoldoutPopup();return `<div class="modal-backdrop soldout-backdrop"><div class="soldout-panel"><span class="soldout-eyebrow">ALL SEATS SOLD OUT</span><div class="soldout-icon">🍇</div><h2>이번 포도알은<br>이미 모두 사라졌어요.</h2><p>치열한 예매 전쟁이었어요.<br><strong>아쉬워요. 민첩한 하루 되세요!</strong></p><div class="soldout-note">다음 공연에서 더 빠르게 도전해봐요.</div><button id="close">다른 공연 예매하기</button></div></div>`}
modal=modalSoldoutPopup;
const modalBeforeSoldoutCopy=modal;
function modalSoldoutCopy(){if(!state.soldout)return modalBeforeSoldoutCopy();return `<div class="modal-backdrop soldout-backdrop"><div class="soldout-panel"><span class="soldout-eyebrow">ALL SEATS SOLD OUT</span><div class="soldout-icon">🍇</div><h2>민첩한 하루 되세요!</h2><p>치열한 예매전쟁이었어요.<br>다음엔 더 빠르게 포도알을 선점하세요!</p><div class="soldout-note">다른 공연에서 다시 도전해봐요.</div><button id="close">다른 공연 예매하기</button></div></div>`}
modal=modalSoldoutCopy;
const modalBeforeSoldoutTitle=modal;
function modalSoldoutTitle(){if(!state.soldout)return modalBeforeSoldoutTitle();return `<div class="modal-backdrop soldout-backdrop"><div class="soldout-panel"><span class="soldout-eyebrow">ALL SEATS SOLD OUT</span><div class="soldout-icon">🍇</div><h2>좌석이 매진되었어요.<br>민첩한 하루 되세요!</h2><p>치열한 예매전쟁이었어요.<br>다음엔 더 빠르게 포도알을 선점하세요!</p><div class="soldout-note">다른 공연에서 다시 도전해봐요.</div><button id="close">다른 공연 예매하기</button></div></div>`}
modal=modalSoldoutTitle;
function enterBookingFlow(){beginBooking()}
function startReadyWait(show){state.show=show;state.hadQueue=false;state.queueStart=0;state.queueJoinDelay=0;state.queueEntrySpeed='';if(show.opening||show.difficulty==='HARD'){state.openingStarted=Date.now();state.countdown=10;state.stage='openwait';state.waitTimer=setInterval(()=>{state.countdown--;if(state.countdown<=0){clearInterval(state.waitTimer);state.countdown=0}render()},1000);render();return}state.readyCountdown=5;state.stage='ready';state.waitTimer=setInterval(()=>{state.readyCountdown--;if(state.readyCountdown<=0){clearInterval(state.waitTimer);state.readyCountdown=0;enterBookingFlow()}else render()},1000);render()}
function bindOpenWaitQueue(){bindNew();document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>startReadyWait(shows.find(s=>s.id===b.dataset.show)));const join=document.querySelector('#joinQueue');if(join)join.onclick=state.show?.difficulty==='HARD'?startHardQueue:startVeryHardQueue}
bind=bindOpenWaitQueue;
function startVeryHardQueueLive(){const openedAt=state.openingStarted+10000,lateSeconds=Math.max(0,(Date.now()-openedAt)/1000),crowdWave=Math.round((Math.sin(Date.now()/700)+1)*900),openingRush=1800+Math.floor(Math.random()*7200)+crowdWave,lateArrival=Math.min(14000,Math.round(lateSeconds*230+Math.pow(lateSeconds,1.25)*42));state.hadQueue=true;state.queueEntrySpeed=lateSeconds.toFixed(2);state.queueJoinDelay=Math.floor(lateSeconds);state.queueNumber=Math.min(24000,openingRush+lateArrival);state.queueStart=state.queueNumber;state.queueBehind=900+Math.floor(Math.random()*8500);state.stage='queue';state.waitTimer=setInterval(()=>{const processed=180+Math.floor(Math.random()*210)+Math.round((Math.sin(Date.now()/430)+1)*55);state.queueNumber=Math.max(0,state.queueNumber-processed);if(Math.random()<.48)state.queueBehind+=15+Math.floor(Math.random()*115);if(Math.random()<.14)state.queueBehind=Math.max(0,state.queueBehind-(8+Math.floor(Math.random()*35)));if(state.queueNumber===0){clearInterval(state.waitTimer);beginBooking()}else render()},500);render()}
function startHardQueueLive(){const openedAt=state.openingStarted+10000;state.hadQueue=true;state.queueJoinDelay=0;state.queueEntrySpeed=Math.max(0,(Date.now()-openedAt)/1000).toFixed(2);state.queueNumber=120+Math.floor(Math.random()*1180);state.queueStart=state.queueNumber;state.queueBehind=40+Math.floor(Math.random()*760);state.stage='queue';state.waitTimer=setInterval(()=>{const processed=55+Math.floor(Math.random()*95);state.queueNumber=Math.max(0,state.queueNumber-processed);if(Math.random()<.43)state.queueBehind+=4+Math.floor(Math.random()*28);if(Math.random()<.12)state.queueBehind=Math.max(0,state.queueBehind-(2+Math.floor(Math.random()*10)));if(state.queueNumber===0){clearInterval(state.waitTimer);beginBooking()}else render()},500);render()}
function queueWaiting(){const progress=Math.max(0,100-Math.round(state.queueNumber/state.queueStart*100));return `<main class="wait-page queue-page"><span class="step">BOOKING QUEUE</span><h1>좌석 선택<br>대기중</h1><p>잠시 기다려주시면 자동 접속됩니다.</p><div class="queue-number">내 대기순서<br><b>${state.queueNumber.toLocaleString()}명</b></div><div class="queue-behind">내 뒤 대기열 <b>${state.queueBehind.toLocaleString()}명</b></div><div class="queue-bar"><i style="width:${progress}%"></i></div><small>접속자가 몰리는 중이에요.</small></main>`}
startVeryHardQueue=startVeryHardQueueLive;
startHardQueue=startHardQueueLive;
queue=queueWaiting;
function bindFriendlySeats(){bindOpenWaitQueue();const legend=document.querySelector('.legend');if(legend)legend.innerHTML='<span><i class="vip"></i>VIP</span><span><i class="s"></i>S</span><span><i class="a"></i>A</span><span><i class="b"></i>B</span><span><i class="used"></i>선택불가</span>';document.querySelectorAll('.seat:not(.locked)').forEach(seat=>seat.onpointerup=event=>{if(state.stage!=='seat')return;event.preventDefault();state.picked=seat.dataset.seat;render()})}
bind=bindFriendlySeats;
function lossDelay(){const [min,max]={ 'VERY HARD':[250,1050],HARD:[450,1500],NORMAL:[700,2100],EASY:[950,2700] }[state.show.difficulty];return min+Math.random()*(max-min)}
function scheduleLoss(){tick();if(!state.soldout&&!state.completed)state.timer=setTimeout(scheduleLoss,lossDelay())}

function shareResult(){const [g]=rank(),canvas=document.createElement('canvas');canvas.width=1080;canvas.height=720;const c=canvas.getContext('2d');c.fillStyle='#182443';c.fillRect(0,0,1080,720);c.fillStyle='#e6ff5c';c.font='bold 68px Arial';c.fillText('FROG TICKET',75,115);c.fillStyle='#fff';c.font='bold 110px Arial';c.fillText(`RANK ${g}`,75,290);c.font='42px Arial';c.fillText(`${state.show.title}`,75,375);c.fillText(`CAPTCHA ${state.captchaTime}s  ·  BOOKING ${state.bookingTime}s`,75,455);const a=document.createElement('a');a.download='frog-ticket-result.png';a.href=canvas.toDataURL('image/png');a.click()}
function makeCaptcha(){let c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join('')}
function verify(){if(document.querySelector('#input').value.trim().toUpperCase()!==state.captcha){toast('보안문자가 일치하지 않아요.');return}state.captchaTime=elapsed();state.stage='seat';if(!allSeats().some(x=>!state.locked.has(x))){clearInterval(state.timer);state.soldout=true}render()}
function tick(){lose();if(!allSeats().some(x=>!state.locked.has(x))){clearInterval(state.timer);state.soldout=true;state.stage='seat';render();return}if(state.stage==='seat')render()}
function allSeats(){return rows.flatMap(([r])=>Array.from({length:10},(_,i)=>r+(i+1)))}
function randomLocked(show){const [min,max]=show.lockedRange;let count=min+Math.floor(Math.random()*(max-min+1));if(show.opening)count+=Math.min(12,Math.floor(state.queueNumber/120));return allSeats().sort(()=>Math.random()-.5).slice(0,count)}
function lose(){const available=allSeats().filter(x=>!state.locked.has(x));const candidates=available.filter(x=>x!==state.picked);if(candidates.length)state.locked.add(candidates[Math.floor(Math.random()*candidates.length)])}
function book(){const remaining=allSeats().filter(x=>!state.locked.has(x));if(remaining.length<=1){clearInterval(state.timer);state.locked.add(state.picked);state.picked=null;state.soldout=true;render();return}if(Math.random()<state.show.loss){state.locked.add(state.picked);state.picked=null;if(!allSeats().some(x=>!state.locked.has(x))){clearInterval(state.timer);state.soldout=true}else state.conflict=true;render();return}clearInterval(state.timer);state.bookingTime=elapsed();const seat=meta(state.picked),seatPoints={VIP:600,R:430,S:270,A:120}[seat[1]],speedBonus=Math.max(0,400-Math.round(Number(state.bookingTime)*25));state.score=seatPoints+speedBonus;state.completed=true;state.stage='seat';render()}
function bookGrade(){const remaining=allSeats().filter(x=>!state.locked.has(x));if(remaining.length<=1){clearInterval(state.timer);state.locked.add(state.picked);state.picked=null;state.soldout=true;render();return}if(Math.random()<state.show.loss){state.locked.add(state.picked);state.picked=null;if(!allSeats().some(x=>!state.locked.has(x))){clearInterval(state.timer);state.soldout=true}else state.conflict=true;render();return}clearInterval(state.timer);state.bookingTime=elapsed();const seat=meta(state.picked),seatPoints={VIP:600,S:430,A:270,B:120}[seat[1]],speedBonus=Math.max(0,400-Math.round(Number(state.bookingTime)*25));state.score=seatPoints+speedBonus;state.completed=true;state.stage='seat';render()}
book=bookGrade;
function resultFullPage(){const seat=meta(state.picked),[grade,message]=rank(),queueInfo=state.hadQueue?`<div><small>QUEUE ENTRY</small><b>${state.queueEntrySpeed}초</b><span>대기열 진입 속도</span></div>`:'';return `<main class="result"><div class="success">✓</div><span class="step">BOOKING COMPLETE</span><h1>예매 완료!</h1><p><b>${state.picked} ${seat[1]}석</b>을 확보했어요.</p><div class="ticket"><div><span>${state.show.title}</span><b>${state.picked}</b><small>${state.show.date}</small></div><i></i><strong>${seat[1]}<small>${seat[2]}</small></strong></div><div class="result-grid"><div><small>COMPETITION</small><b>약 ${competitionRate()} : 1</b><span>이번 예매 경쟁률</span></div>${queueInfo}<div><small>BOOKING TIME</small><b>${state.bookingTime}초</b><span>예매 완료까지</span></div></div><div class="rank-result"><span>YOUR RANK</span><b>${grade}</b><div><strong>${message}</strong><p>보안문자 ${state.captchaTime}초 · ${state.score} PT</p></div></div><button class="cta" id="restart">공연 목록으로</button></main>`}
result=resultFullPage;
function resultTicketRankStats(){const seat=meta(state.picked),[grade,message]=rank(),queueInfo=state.hadQueue?`<div><small>QUEUE ENTRY</small><b>${state.queueEntrySpeed}초</b><span>대기열 진입 속도</span></div>`:'';return `<main class="result"><div class="success">✓</div><span class="step">BOOKING COMPLETE</span><h1>예매 완료!</h1><p><b>${state.picked} ${seat[1]}석</b>을 확보했어요.</p><div class="ticket"><div><span>${state.show.title}</span><b>${state.picked}</b><small>${state.show.date}</small></div><i></i><strong>${seat[1]}<small>${seat[2]}</small></strong></div><section class="full-rank"><small>YOUR RANK</small><b>${grade}</b><strong>${message}</strong><p>이번 예매 실력 인증 완료!</p></section><div class="result-grid result-stats"><div><small>COMPETITION</small><b>약 ${competitionRate()} : 1</b><span>이번 예매 경쟁률</span></div>${queueInfo}<div><small>BOOKING TIME</small><b>${state.bookingTime}초</b><span>예매 완료까지</span></div><div><small>CAPTCHA TIME</small><b>${state.captchaTime}초</b><span>보안문자 해독 시간</span></div></div><button class="cta" id="restart">공연 목록으로</button></main>`}
result=resultTicketRankStats;
function resultTicketDetails(){const seat=meta(state.picked),[grade,message]=rank(),reaction=state.queueEntrySpeed||'0.00';return `<main class="result"><div class="success">✓</div><span class="step">BOOKING COMPLETE</span><h1>예매 완료!</h1><p><b>${state.picked} ${seat[1]}석</b>을 확보했어요.</p><section class="ticket ticket-card"><div class="ticket-top"><small>공연명 · 공연일</small><b>${state.show.title}</b><small>${state.show.date}</small></div><div class="ticket-meta"><div><small>등급 · 좌석</small><b>${seat[1]} · ${state.picked}석</b></div><div><small>금액</small><strong>${seat[2]}</strong></div></div></section><section class="full-rank"><small>YOUR RANK</small><b>${grade}</b><strong>${message}</strong><p>이번 예매 실력 인증 완료!</p></section><div class="result-grid result-stats"><div><small>COMPETITION</small><b>${competitionRate()} : 1</b><span>경쟁률</span></div><div><small>BOOKING TIME</small><b>${state.bookingTime}초</b><span>예매 완료</span></div><div><small>CAPTCHA TIME</small><b>${state.captchaTime}초</b><span>보안문자</span></div><div><small>START REACTION</small><b>${reaction}초</b><span>시작 반응</span></div></div><button class="cta" id="restart">공연 목록으로</button></main>`}
result=resultTicketDetails;
function resultTicketClean(){const seat=meta(state.picked),[grade,message]=rank(),reaction=state.queueEntrySpeed||'0.00';return `<main class="result"><div class="success">✓</div><span class="step">BOOKING COMPLETE</span><h1>예매 완료!</h1><p><b>${state.picked} ${seat[1]}석</b>을 확보했어요.</p><section class="ticket ticket-card"><div class="ticket-top"><b>${state.show.title}</b><span class="ticket-date">${state.show.date}</span></div><div class="ticket-meta"><div><b>${seat[1]} · ${state.picked}석</b></div><div><strong>${seat[2]}</strong></div></div></section><section class="full-rank"><small>YOUR RANK</small><b>${grade}</b><strong>${message}</strong><p>이번 예매 실력 인증 완료!</p></section><div class="result-grid result-stats"><div><small>COMPETITION</small><b>${competitionRate()} : 1</b><span>경쟁률</span></div><div><small>BOOKING TIME</small><b>${state.bookingTime}초</b><span>예매 완료</span></div><div><small>CAPTCHA TIME</small><b>${state.captchaTime}초</b><span>보안문자</span></div><div><small>START REACTION</small><b>${reaction}초</b><span>시작 반응</span></div></div><button class="cta" id="restart">공연 목록으로</button></main>`}
result=resultTicketClean;
function bookResultPage(){const remaining=allSeats().filter(x=>!state.locked.has(x));if(remaining.length<=1){clearInterval(state.timer);state.locked.add(state.picked);state.picked=null;state.soldout=true;render();return}if(Math.random()<state.show.loss){state.locked.add(state.picked);state.picked=null;if(!allSeats().some(x=>!state.locked.has(x))){clearInterval(state.timer);state.soldout=true}else state.conflict=true;render();return}clearInterval(state.timer);state.bookingTime=elapsed();const seat=meta(state.picked),seatPoints={VIP:600,S:430,A:270,B:120}[seat[1]],speedBonus=Math.max(0,400-Math.round(Number(state.bookingTime)*25));state.score=seatPoints+speedBonus;state.completed=true;state.stage='result';render()}
book=bookResultPage;
function renderResultPage(){const view=state.stage==='list'?list():state.stage==='ready'?readyScreen():state.stage==='openwait'?openwait():state.stage==='queue'?queue():state.stage==='captcha'?captcha():state.stage==='seat'?seats():result();app.innerHTML=`<div class="phone"><header><b>FROG TICKET <i>GAME</i></b></header>${state.stage!=='list'&&state.stage!=='result'?'<div class="progress"><i></i><i class="on"></i><i></i></div>':''}${view}</div>${state.conflict||state.soldout?modal():''}<div class="toast" id="toast"></div>`;bind()}
render=renderResultPage;
function reset(){clearInterval(state.timer);clearInterval(state.waitTimer);rows=allRows.slice(0,4);Object.assign(state,{stage:'list',show:null,picked:null,started:0,captchaTime:0,bookingTime:0,score:0,locked:new Set(baseLocked),captcha:'',timer:null,waitTimer:null,countdown:0,readyCountdown:0,queueNumber:0,queueStart:0,conflict:false,soldout:false,completed:false});render()}
function toast(x){let e=document.querySelector('#toast');if(!e)return;e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}render();
